# Generated by Django 3.2.3 on 2021-05-19 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCreated', models.DateTimeField(default=datetime.datetime.now)),
                ('imageInput', models.ImageField(blank=True, null=True, upload_to='')),
                ('imageOutput', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
