# Generated by Django 3.2.3 on 2021-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='alpha',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='entry',
            name='blockSize',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='entry',
            name='tm',
            field=models.DecimalField(decimal_places=5, default=0.001, max_digits=6),
        ),
    ]
