# Generated by Django 3.0.5 on 2021-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210519_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-timeCreated']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='alpha',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='entry',
            name='blockSize',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='imageInput',
            field=models.ImageField(blank=True, null=True, upload_to='input/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='imageOutput',
            field=models.ImageField(blank=True, null=True, upload_to='output/'),
        ),
    ]
